language: csharp
solution: Oracular.sln

mono:
  - latest
  - 3.10.0
  - 3.8.0

  - alpha
  - beta
  - nightly

matrix:
  allow-failures:
    - mono: alpha
    - mono: beta
    - mono: nightly

install:
  - travis_retry nuget restore Oracular.sln
  - travis_retry nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Oracular.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Oracular.Tests/bin/Release/Oracular.Tests.dll
